Reattempt part upload upon failure
tbumi/glacier-upload pull request #4
Opened 2017-09-18 01:37 UTC by azeemba

When a part upload fails, we should retry since a lot of the issues
can be transient.

Fixes #2

2017-09-24 00:20 UTC, azeemba commented
Any thoughts on #3 and #4 @tbumi?

2017-09-26 06:00 UTC, tbumi requested changes
I left some suggestions, feel free to comment if you have any questions.

2017-09-26 06:00 UTC, tbumi commented on main.py
> +    MAX_ATTEMPTS = 10
Constants should be defined outside of functions.

2017-09-26 06:00 UTC, tbumi commented on main.py
> +    for i in range(MAX_ATTEMPTS):
instead of setting variable `uploaded`, how about using `for..else`?

2017-09-26 06:00 UTC, tbumi commented on main.py
> +            assert checksum == response['checksum'], 'Checksums do not match.'
instead of asserting, just use an `if` condition to check: if checksums match, then break from loop.

2017-09-27 23:38 UTC, azeemba commented on main.py
> +            assert checksum == response['checksum'], 'Checksums do not match.'
The previous code was asserting so I stuck with that. Are you sure you want to change that behavior?

2017-09-28 03:40 UTC, tbumi commented on main.py
> +            assert checksum == response['checksum'], 'Checksums do not match.'
Yeah, I plan to change some code styles myself anyways.

2017-09-28 03:42 UTC, tbumi approved these changes
Cool. Thanks for the contribution, I will merge this PR.

2017-09-28 03:42 UTC, merged